### ISSUE TITLE
Apollo fragment placeholder in gql template literal removed during format lines

### ISSUE THREAD

**Issue by jakubkulhan** [jimkyndemeyer/js-graphql-intellij-plugin#162] opened 2018-05-29 08:45 UTC
After upgrading plugin to 1.7.1, when I run reformat, interpolations are removed from GraphQL template literals.

E.g. if I have such interpolation with fragment from other component:

<img width="251" alt="snimek obrazovky 2018-05-29 v 10 41 48" src="https://user-images.githubusercontent.com/95001/40647854-358e1f20-632d-11e8-9f6c-a3ebf4140f0a.png">

and then I run reformat:

<img width="238" alt="snimek obrazovky 2018-05-29 v 10 41 59" src="https://user-images.githubusercontent.com/95001/40647898-56ad3d8a-632d-11e8-8c46-a526aa5fb5db.png">

Interpolation of the fragment is removed from the literal.

**Comment by jimkyndemeyer** [comment] 2018-05-29 12:19
Hi Jakub.

Thanks for reporting this.

I was initially unable to reproduce this, but it appears to be linked to the use of decorators.

**Comment by jimkyndemeyer** [comment] 2018-05-29 18:06
Hi Jakub.

This is fixed in 1.7.2, pending JetBrains approval.

**Closed by jimkyndemeyer** 2018-05-29 18:06 UTC

**Comment by stonecold123** [comment] 2018-05-31 04:36
I have the same problem when moving the template literals to another file.

**Comment by jimkyndemeyer** [comment] 2018-05-31 05:34
@stonecold123 Pasting into another file also triggers formatting, so the incoming fix should address this as well. JetBrains typically approves plugin updates within two days, so it's likely that the update will be available today.

**Comment by jimkyndemeyer** [comment] 2018-06-03 18:42
Approved by JetBrains. The 1.7.2 update should be available now when searching for plugin updates.
