### ISSUE TITLE
Work with GraphQL VSCode plugin author to standardize config file support 

### ISSUE THREAD

**Issue by UselessPickles** [jimkyndemeyer/js-graphql-intellij-plugin#428] opened 2021-01-19 20:14 UTC
I work with a team of developers who have mixture of using IntelliJ and VSCode IDEs, so we try to always setup our projects and processes to work equally well in both IDEs. This is proving to be a challenge when configuring GraphQL plugins, because the plugins available for both IDEs have some incompatibilities in how they find config files.

I am proposing that the authors of both projects should work together to agree on some level of commonality/standardization so that a project can be setup to use both plugins without duplicating configuration files.

"GraphQL" plugin for VSCode: https://github.com/graphql/vscode-graphql
"JS GraphQL" plugin for IntelliJ: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

## Actual Behavior
The "JS GraphQL" plugin for IntelliJ and the "GraphQL" plugin for VSCode cannot read the same config file. Some key differences are:

1. "JS GraphQL" plugin for IntelliJ requires a config file named ".graphqlconfig", but the "GraphQL" plugin for VSCode does not support a config file with that name. For a bare minimum of consistency, at least one of the plugins would need to be enhanced to create at least some overlap in supported file names/formats.
2.  "JS GraphQL" plugin for IntelliJ conveniently [supports multiple config files for nested "sub-projects"](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide#setting-up-multi-schema-projects-using-graphql-config). The plugin finds all config files all throughout the project directory structure, and automatically assumes that each config file applies to the directory it was found in (and its sub-directories). "GraphQL" plugin for VSCode only supports a single config file, so you are forced to create a single config file that defines the multiple nested "projects". It would be nice if the "GraphQL" plugin for VSCode could be enhanced to find/process all config files throughout the directory structure like "JS GraphQL" plugin for IntelliJ does.

## Expected Behavior
The "JS GraphQL" plugin for IntelliJ and the "GraphQL" plugin for VSCode should be able to read the same config file, from the same place within the project.

## Related Issues

- [Corresponding issue for "GraphQL" VSCode plugin project](https://github.com/graphql/vscode-graphql/issues/274)

**Comment by mattalexander-pantheon** [comment] 2021-05-19 13:09
This problem stems from the fact that this plugin is still using the legacy version of `graphql-config`:

https://github.com/kamilkisiela/graphql-config/tree/legacy

**Comment by vepanimas** [comment] 2021-07-21 01:53
@mattalexander-pantheon it is true, the transition to the current version is one of the most priority tasks in the roadmap.

**Comment by vepanimas** [comment] 2021-07-21 01:57
I think I could close it as a duplicate of this task https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/296.

**Closed by vepanimas** 2021-07-21 01:57 UTC
