### ISSUE TITLE
"GraphQL Configuration Scan" doesn't finish until indices start.

### ISSUE THREAD

**Issue by Floffah** [jimkyndemeyer/js-graphql-intellij-plugin#352] opened 2020-07-18 09:56 UTC
**Before you create the issue**
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions
- Please search the [existing issues](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc) before opening a new issue
- Review the [developer guide](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide)
- Review the [example projects](https://github.com/jimkyndemeyer/graphql-config-examples)

**Describe the bug**
When on Webstorm 2020.1.3 or 2020.2, the Updating Indices task starts after GraphQL Configuration Scan and because of this, neither finish as Indicies is paused and the config scan must rely on it.
![](https://i.imgur.com/10oqxDz.png)
Both only finish once i press the play button on Updating Indices

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
1. Install plugin
2. Create a plugin
3. Watch this window
![](https://i.imgur.com/10oqxDz.png)
4. Nothing happens until you press play on updating indices

**Expected behavior**
Updating Indices and GraphQL Configuration Scan should finish when done

**Screenshots**
![](https://i.imgur.com/10oqxDz.png)

**Version and Environment Details**
Operation system: Windows 10 Pro latest (possibly 1909)
IDE name and version: WebStorm 2020.1.3 & 2020.2 EAP
Plugin version: 2.5.0

**Comment by vepanimas** [comment] 2020-09-01 18:01
Hi @Floffah!

Did you mean "Create a project" in the second item of the steps to reproduce? If so, it's possible that indexing is paused due to the project bootstrapping, e.g. `create-react-app` pauses indexing during its execution. When the initial bootstrapping of the project is complete, indexing should start automatically, followed by a configuration search.

**Comment by geisterfurz007** [comment] 2020-09-01 20:13
If that helps, I have the same issue in Angular projects (substitute 2. with "New > Angular Schematic > component"). It's not influenced by some other process; even 5 minutes after the files are all generated, this issue persists until you click the play button manually. It seems that the two interfere in a way that they believe the other one should go first thus not finishing until forcing Indexing to complete.

**Comment by vepanimas** [comment] 2020-09-01 20:15
@geisterfurz007 ok, thanks! Will try to reproduce it.

**Comment by Floffah** [comment] 2020-09-01 20:22
@vepanimas i only have this issue when i choose nodejs app in the create new project window

**Comment by Floffah** [comment] 2020-09-01 20:22
i can confirm this still happens after 2020.2.1 was released

**Comment by vepanimas** [comment] 2021-11-19 21:15
Should be fixed in 3.0.0.

**Closed by vepanimas** 2021-11-19 21:15 UTC
Labels: enhancement
