### ISSUE TITLE
Go to Definition always scrolls to the top of the schema

### ISSUE THREAD

**Issue by AOrobator** [jimkyndemeyer/js-graphql-intellij-plugin#289] opened 2019-09-12 15:44 UTC
## Version and Environment Details
__Operation system__: Mac OS 10.14.6

__IDE name and version__: 
Android Studio 3.5

__Plugin version__: 
v2.2.0

## Expected Behaviour
When I invoke go to definition on a graphql query I'm editing, I expect to be taken to the point in the schema where the property I'm interested in is defined.

## Actual Behaviour
Schema always scrolls to top of file.

**Comment by jimkyndemeyer** [comment] 2019-09-13 16:41
The JetBrains team will take a look at this in https://youtrack.jetbrains.com/issue/IDEA-222678

**Comment by AOrobator** [comment] 2019-09-14 03:04
Thanks for the update! At least there's a workaround for now.

**Comment by denofevil** [comment] 2019-09-17 12:25
@jimkyndemeyer looks like the problem is caused by https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/src/main/com/intellij/lang/jsgraphql/v1/ide/project/JSGraphQLLanguageUIProjectService.java#L253 which scrolls editor to the very beginning.

**Comment by jimkyndemeyer** [comment] 2019-09-17 12:38
@denofevil Ah, thanks. good catch. I think the issue is that the newly inserted header pushes some of the editor lines outside of the view. I'll see if I can figure out a way to simply restore the scroll position to what it was before the header was inserted.

**Comment by danez** [comment] 2019-10-14 09:31
The same also happens in PHPStorm.

**Comment by jimkyndemeyer** [comment] 2019-12-14 19:02
Fixed in the upcoming 2.3.0.

**Closed by jimkyndemeyer** 2019-12-14 19:02 UTC
