### ISSUE TITLE
Reserved keyword `on` ?

### ISSUE THREAD

**Issue by smeevil** [jimkyndemeyer/js-graphql-intellij-plugin#264] opened 2019-07-01 12:53 UTC
It seems that `on` is handled as a reserved keyword. I'm not sure if this is actually the case, but I could not find any information about graphql schemas and reserved keywords.

__Operation system__: macOS Mojave 10.14.5

__IDE name and version__: IntelliJ 2019.2 EAP

__Plugin version__: 2.2.0

## Expected Behaviour

Given the following schema.graphql snippet :

```
type Foo {
  bar(on: Date): [Baz!]!
}
```

I would expect the `on` to be regarded as a regular variable.

## Actual Behaviour

It now throws with `unexpected token 'on'`
If I rename the `on` variable to `onn` for example, it parses fine.

**Comment by PowerKiKi** [comment] 2019-08-08 18:12
This seems to be a duplicate of #239

**Comment by smeevil** [comment] 2019-09-09 13:10
Hi,

I was wondering if this is still on the radar?

**Comment by jimkyndemeyer** [comment] 2019-09-09 13:56
I plan on fixing this eventually, but It depends on a similar fix in graphql-java 14.0 which hasn't been released yet.

**Comment by smeevil** [comment] 2019-09-09 14:01
Thanks for getting back, I'll practice some more patience :)

**Comment by jimkyndemeyer** [comment] 2020-03-13 12:14
Fixed in the upcoming 2.4.0.

**Closed by jimkyndemeyer** 2020-03-13 12:14 UTC

**Comment by smeevil** [comment] 2020-03-13 13:49
awesome ! thank you !
