### ISSUE TITLE
Deprecated directive not parsing in GQL template literal.

### ISSUE THREAD

**Issue by nmaves** [jimkyndemeyer/js-graphql-intellij-plugin#328] opened 2020-03-31 14:08 UTC
## Before you create the issue
- Please search the existing issues at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc before opening a new issue.
- Read the FAQ at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions.

## Version and Environment Details
__Operation system__: OS X

__IDE name and version__: Webstorm 2020.1

__Plugin version__: 2.4.0

## Expected Behaviour
No syntax errors.

## Actual Behaviour

<img width="636" alt="hoopla-graphql_–_schema_js" src="https://user-images.githubusercontent.com/367750/78035751-bf150a00-7326-11ea-94ec-541370f5eff3.png">

**Comment by vepanimas** [comment] 2020-09-13 18:46
@nmaves a lot of related issues were fixed in 2.5.0 and 2.6.0, so now I can't reproduce this one. If this problem is still reproducing for you, please, comment or reopen that issue.

**Closed by vepanimas** 2020-09-13 18:46 UTC
