### ISSUE TITLE
[v2] Syntax highlight not working

### ISSUE THREAD

**Issue by pulse14** [jimkyndemeyer/js-graphql-intellij-plugin#237] opened 2019-04-09 08:50 UTC
## Version and Environment Details
__Operation system__: Windows
__IDE name and version__:  IntelliJ IDEA 2019.1.1 Preview (Ultimate Edition)
Build #IU-191.6707.7, built on April 2, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

__Plugin version__:  2.0.0

## Expected Behaviour
Syntax highlight working
## Actual Behaviour
Syntax highlight not working
## Steps to Reproduce / Link to Repo with Reproduction and Instructions
- Install the plugin 
- Open .graphql file

**Comment by jimkyndemeyer** [comment] 2019-04-09 09:01
Hi Gaetan.

Thanks for using the plugin.

Do you see any red error icons blinking in the bottom right? If so, please click it and attach the stack trace to this issue.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment] 2019-04-09 16:41
Hi.

I've installed 2019.1.1 to reproduce, but the editor colors work as expected.

Could you please export your relevant settings:
- "File" menu > "Export settings"
- Only check "Code Style (schemes)", "Editor Colors" and "Look and feel"
- Click OK and attach the zip file to this issue

**Comment by pulse14** [comment] 2019-04-10 07:41
[settings.zip](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/3062546/settings.zip)

**Comment by jimkyndemeyer** [comment] 2019-04-13 10:14
Hi @pulse14 

Thanks for the settings.

Like many other languages, the GraphQL syntax highlighter falls back to the colors that have been defined in the "Language Defaults". When I imported your settings I got the following:

![image](https://user-images.githubusercontent.com/15837712/56078158-ff613c80-5de4-11e9-89de-8b6f12965aed.png)

So this is not a bug in the plugin, but due to a number of the default colors being set to plain white. You'll likely see "missing colors" in other languages a well.

As for next steps you can either edit the language default colors or override as needed in the GraphQL colors page.

Also, I don't know whether you've setup the "Monokai Sublime" colors, but you could consider filing a bug report if the colors are maintained by someone else. In its current state other plugins will also show their keywords etc. as plain white.

I'm closing this as "not a bug" since the highlighter works as intended using the colors its given.

Let me know if you have any questions.

Best regards,
Jim.

**Closed by jimkyndemeyer** 2019-04-13 10:14 UTC

**Comment by pulse14** [comment] 2019-04-13 10:35
Thank you for your help  ! 
I think the last intellij update changed all my colors... I thought it was the plugin because I updated it at the same time.

**Comment by mikeerickson** [comment] 2019-08-21 20:40
I am experiencing a similar issue using PHPStorm (latest build) along with Material Theme.  In my case, much like OP, there is no syntax highlighting.  Further, whenever, I restart PHPStorm, it wants me to install the plugin again

**Comment by jimkyndemeyer** [comment] 2019-08-22 17:07
@mikeerickson I just tested with the Material Theme UI plugin and it highlights as expected:

![image](https://user-images.githubusercontent.com/15837712/63534462-88b11a00-c50f-11e9-8626-3447466834d9.png)

Please review your "Language Default" syntax colors as these are inherited by the GraphQL highlighter.

As for the plugin install issue, try and reinstall the plugin. If that doesn't work I would log a ticket with JetBrains since they maintain the plugin installation itself.

Best regards,
Jim.

**Comment by mikeerickson** [comment] 2019-08-22 18:31
@jimkyndemeyer Looks the same here (see the background of .schema file)  What have you defined as the associated file type for `.schema` files?

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/183153/63540127-5c29dd80-c4d0-11e9-838e-4ff0e6de6a4f.png">

**Comment by mikeerickson** [comment] 2019-08-22 18:33
@jimkyndemeyer I have my `.schema` files associated with `GraphQL Doc` (have also tried `GraphQL` and `GraphQL Endpoint`)

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/183153/63540237-9abf9800-c4d0-11e9-83e1-ebbfdfe6c31d.png">
