### ISSUE TITLE
Support descriptions

### ISSUE THREAD

**Issue by estaub** [jimkyndemeyer/js-graphql-intellij-plugin#157] opened 2018-05-18 02:44 UTC
[The graphql spec](http://facebook.github.io/graphql/draft/#sec-Descriptions) describes how a quoted string (including block quotes) can be used as a description.

graphql-cli now emits block-quoted descriptions in schema.

**Comment by SPAHI4** [comment] 2018-05-21 13:10
I also have a syntax error on it with `relay-compiler`

**Comment by tamlyn** [comment] 2018-05-25 12:50
Duplicate of #118

**Comment by jimkyndemeyer** [comment] 2018-07-19 05:32
Supported in v2. Closing as duplicate of #118

**Closed by jimkyndemeyer** 2018-07-19 05:32 UTC
