### ISSUE TITLE
Unable to start JS GraphQL Language Service using Node.js

### ISSUE THREAD

**Issue by justinhandley** [jimkyndemeyer/js-graphql-intellij-plugin#190] opened 2018-11-17 23:18 UTC
## Version and Environment Details
__Operation system__: 
Mac OS Mojave 10.14.1
__IDE name and version__: 
Intellij Idea 2018.2
__Plugin version__: 
1.7.2
## Expected Behaviour

Start Intelllij and the plugin works

## Actual Behaviour

I've checked and seen other similar issues, but no discussed fixes actually get this working for me.

Start Intellij and get this:

java.lang.Throwable: Unable to start JS GraphQL Language Service using Node.js with commandline /Users/justinhandley/.nvm/versions/node/v8.11.1/bin/node [--no-deprecation, /Users/justinhandley/Library/Application Support/IntelliJIdea2018.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js, --port=53826]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.createProcessHandler(JSGraphQLNodeLanguageServiceInstance.java:148)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.restart(JSGraphQLNodeLanguageServiceInstance.java:187)
	at com.intellij.lang.jsgraphql.ide.project.JSGraphQLLanguageUIProjectService.restartInstance(JSGraphQLLanguageUIProjectService.java:601)
	at com.intellij.lang.jsgraphql.ide.actions.JSGraphQLRestartLanguageServiceAction.actionPerformed(JSGraphQLRestartLanguageServiceAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:255)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:204)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:146)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:391)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jimkyndemeyer** [comment] 2018-11-18 16:54
Hi Justin.

Thanks for using the plugin.

There should be a cause further down in the full stack trace. Please add that to the issue.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment] 2018-11-19 05:53
Hi Justin.

To clarify, I'm looking for the part of the stack trace that is below "caused by", which is where reason for the exception that was thrown is found. It should be present if you include the entire stack trace.

**Comment by justinhandley** [comment] 2018-11-19 14:03
Hi There - sorry, I don't mean to be thick, but how do I find that?  This is everything that Intellij is giving me - is there a place I can look for a more detailed stack trace?

**Comment by justinhandley** [comment] 2018-11-19 15:48
If I run this

 /Users/justinhandley/.nvm/versions/node/v8.11.1/bin/node  /Users/justinhandley/Library/Application\ Support/IntelliJIdea2018.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js

I get this

/Users/justinhandley/Library/Application Support/IntelliJIdea2018.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:68
    throw error;
    ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

**Comment by justinhandley** [comment] 2018-11-19 15:57
Hi There - after looking at this, I tried pinging localhost, and then found that my /etc/hosts file didn't have the right values in it for localhost.  I added those, and the issue is resolved.  I wonder, though, if it wouldn't make sense to handle an error where the graphcool service can't be found without having it report a crash in the IDE, instead just giving a message in the graphcool console that the service can't be found?

**Comment by jimkyndemeyer** [comment] 2018-11-19 16:14
Hi Justin.

Thanks for the update.

Yeah, this error reporting isn't ideal. Luckily, V2 uses Java GraphQL tooling and doesn't have to communicate with an external Node.js handler that can be affected by environment issues such as this.

I'll close the issue on that basis.

**Closed by jimkyndemeyer** 2018-11-19 16:14 UTC
