### ISSUE TITLE
After the most recent update, fragment fields are being seen as unknown

### ISSUE THREAD

**Issue by xxx** [jimkyndemeyer/js-graphql-intellij-plugin#386] opened 2020-09-09 20:33 UTC
After a plugin upgrade a couple of days ago, I have fragments that are showing that they have invalid fields. The fragments are working fine and were correctly handled in the previous version.

**Expected behavior**
The fragments are found in the schema and highlighted correctly.

**Screenshots**
![Screenshot from 2020-09-09 13-31-09](https://user-images.githubusercontent.com/41678/92650050-d1fe1400-f2a0-11ea-9dc4-3327d0a5ac81.png)

**Version and Environment Details**
Operation system: Linux vatican 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
IDE name and version: RubyMine 2020.2
Plugin version: 2.6.0

**Comment by vepanimas** [comment] 2020-09-09 22:30
@xxx hi, thank you for the report. Unfortunately, I can't reproduce it, I have an example project with GitHub schema, everything works there. I need more information about your project configuration, .graphqlconfig and an example schema for which fragments don't work.

**Comment by xxx** [comment] 2020-09-10 00:48
@vepanimas Hi, thank you for responding. Is the example project online? These fragments are multiple levels deep, which is one point of complexity that most examples won't contain.

**Comment by xxx** [comment] 2020-09-10 00:49
@vepanimas hm, now they are rendering ok, even though nothing has changed. I guess I'll close this, but this was very strange behavior.

**Comment by vepanimas** [comment] 2020-09-10 01:32
@xxx ok, if you encounter this problem again feel free to reopen this issue. Also, I know about some existing problems with caching now, which possibly could lead to this behavior, I hope to fix them in next releases. But I'm not sure about your case though, because restart usually fixes them.

**Comment by a-sane** [comment] 2020-09-14 11:06
@vepanimas @xxx I have the same problem

![image](https://user-images.githubusercontent.com/764967/93078544-52eb5000-f693-11ea-89a6-b2ff4c691d2d.png)

Version and Environment Details
Operation system: macOS Mojave 10.14.6
IDE name and version: WebStorm 2020.2
Plugin version: 2.6.0

**Comment by vepanimas** [comment] 2020-09-14 13:54
@a-sane hi, do any other schema errors in the GraphQL tab? Any information could be useful. Also, have you tried invalidating caches? Of course, this is not a solution, but it's better to know if caching or something else is affecting it.

**Comment by a-sane** [comment] 2020-09-14 15:01
@vepanimas 

if I understood correctly there is no errors in the GraphQL tab:
![image](https://user-images.githubusercontent.com/764967/93102255-f2b8d600-f6b3-11ea-851a-2095fc17cbc3.png)

I'm tried invalidating caches, still no luck. Also sometimes this error randomly disappear and then appear again.
I can't figure out how to reproduce this stably.

.graphqlconfig:

```js
{
  "schemaPath": "schema.graphql",
  "includes": ["*.graphql", "*.js"],
  "excludes": ["node_modules/**"]
}
```

**Comment by vepanimas** [comment] 2021-02-19 19:10
@a-sane @xxx is it still reproduced? I fixed some issues similar to that one, so I'm not sure if it's still relevant.

**Comment by xxx** [comment] 2021-02-19 20:39
@vepanimas I just updated to 2.8.0 this morning, but things seem good so far.

**Comment by vepanimas** [comment] 2021-02-20 02:44
Then I'll close it for now. If similar problems arise, feel free to comment here or open a new issue.

**Closed by vepanimas** 2021-02-20 02:44 UTC
Labels: bug
