### ISSUE TITLE
[v2] There is no top level schema object defined

### ISSUE THREAD

**Issue by simPod** [jimkyndemeyer/js-graphql-intellij-plugin#168] opened 2018-07-05 23:18 UTC
If I understood correctly, the plugin is looking for `schema` directive which is not generated by my server as defaults are used. The [docs](http://facebook.github.io/graphql/June2018/#sec-Schema) says the `schema` directive is optional so I think that the plugin should try to find `Query`, `Mutation` and `Subscription` types by default if not returned by introspection.

![image](https://user-images.githubusercontent.com/327717/42352266-eff312a6-80c1-11e8-8f6f-5bab3052f13e.png)

**Comment by jimkyndemeyer** [comment] 2018-07-06 06:17
If you don't have a schema directive and have a Query type, this error indicates that the file your has not discovered the Query type definition.

If you're using the single schema option in GraphQL settings, then this is a bug, and I'd like a minimal    project that reproduces.

If you using scopes or graphql-config, please review your settings and ensure this file is associatd with the schema file that contains the query type. On that note, if this is the case, you should see a yellow warning bar on top of the editor. Can you confirm that you see one?

**Comment by simPod** [comment] 2018-07-06 07:09
I'm using the graphqlconfig option

This is the content:

```json
{
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost/graphql/",
        "headers": {
          "user-agent": "JS GraphQL"
        }
      }
    }
  }
}
```

The endpoint http://localhost/graphql/ is working well, I thought that the plugin would do introspection throught this endpoint

When I press the arrow 
![image](https://user-images.githubusercontent.com/327717/42364634-78eb2b92-8104-11e8-9947-2ce6c4c5b6a3.png)
it says 
> GraphQL Configuration Error: No schemaPath found for url http://localhost/graphql/

**Comment by jimkyndemeyer** [comment] 2018-07-06 09:42
The workflow is somewhat different in v2 given that it relies on graphql-config.

I'll see if I can find some time to write up some minimal docs in the near future.

So the workflow with graphql-config is that you configure a `schemaPath` in your `.graphqlconfig`. When you run the introspection query by clicking on the arrow, the result is written to the file defined by the `schemaPath`, e.g.:

```json
{
  "shemaPath": "./schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost/graphql/",
        "headers": {
          "user-agent": "JS GraphQL"
        }
      }
    }
  }
}
```

**Comment by simPod** [comment] 2018-07-06 10:07
With that it works, thanks

**Comment by jimkyndemeyer** [comment] 2018-07-06 11:13
Ok. I'll keep this issue open, as the plugin could provide better error messages, and help with the creation of a `schemaPath` in case it's missing.

**Comment by lehresman** [comment] 2018-08-17 12:25
Looks like my Rails graphql engine is receiving these parameters when the plugin is trying to query the schema:

```
{"query"=>"http://localhost:3000/graphql/private", "graphql"=>{"query"=>"http://localhost:3000/graphql/private"}}
```

Looks like a valid query is not being passed.

**Comment by lehresman** [comment] 2018-08-17 12:30
Ok, nevermind.  I had some bogus configuration in the GraphQL settings panel.

**Comment by jimkyndemeyer** [comment] 2019-03-10 14:43
Closing this as the plugin now has a "Schemas and Project Structure" UI that provides a better schema discovery status. I've also defaulted new .graphqlconfig files to have a default `schemaPath`.

**Closed by jimkyndemeyer** 2019-03-10 14:43 UTC
Labels: v2-alpha, v2-architecture

**Comment by fracmak** [comment] 2019-06-11 19:08
I've run into an issue where this error pops up if the schema you're referred to is inside a folder that's been excluded from the IDE. For whatever reason the plugin can't find it or parse it properly. Would be nice if it could explain that's what's going on
