### ISSUE TITLE
v2.2.0 IllegalArgumentException on startup renders IDE unusable

### ISSUE THREAD

**Issue by kalbert312** [jimkyndemeyer/js-graphql-intellij-plugin#261] opened 2019-06-23 21:45 UTC
## Version and Environment Details
__Operation system__: macOS 10.14.5

__IDE name and version__: WebStorm 2019.1.3

__Plugin version__: 2.2.0

## Expected Behaviour
IDE starts up.

## Actual Behaviour
```
java.lang.IllegalArgumentException: window with id="GraphQL" is already registered
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.java:1039)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.java:1019)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.java:1008)
	at com.intellij.lang.jsgraphql.v1.ide.project.toolwindow.JSGraphQLLanguageToolWindowManager.init(JSGraphQLLanguageToolWindowManager.java:61)
	at com.intellij.lang.jsgraphql.v1.ide.project.JSGraphQLLanguageUIProjectService.lambda$null$9(JSGraphQLLanguageUIProjectService.java:608)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

2 projects open.
Not exactly sure what's causing it... can't seem to reproduce it now, but the only way to stop it from happening without disabling the plugin is to restart WebStorm.

**Comment by jimkyndemeyer** [comment] 2019-06-24 06:53
Hi Kyle.

Thanks for using the plugin.

Could you please try to uninstall and reinstall the plugin. Historically this has been an issue with the plugin being loaded twice after WebStorm has updated it to a new version.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment] 2019-07-15 17:26
Assuming the thumbs up indicates the issue is fixed. Closing on that basis.

**Closed by jimkyndemeyer** 2019-07-15 17:26 UTC
