### ISSUE TITLE
Single GQL file; "﻿[...] type, tried to redefine existing [...] type"

### ISSUE THREAD

**Issue by haf** [jimkyndemeyer/js-graphql-intellij-plugin#288] opened 2019-09-09 14:44 UTC
## Before you create the issue
- Please search the existing issues at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc before opening a new issue. DONE
- Read the FAQ at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq — broken link
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions. – done

## Description

I have a GraphQL file that gets written from a build script; when it is written from the background, all interfaces and types and unions are marked as duplicates. I can add another interface to the same file, or rename an existing interface in the file, and it gets unmarked as a duplicate. Renaming it back marks it as duplicate.

Enums are not marked to be duplicated.

I've tried clear caches & restart, to no avail.
I've tried uninstalling the plugin and installing it again, and that removed the duplication warnings for the types, but not unions/interfaces, but when rewriting/overwriting the document with the build script in the background, the types are marked as duplicates again.

## Version and Environment Details
__Operation system__:  macOS
__IDE name and version__: Rider 2019.2.2
__Plugin version__: 2.2.0

## Expected Behaviour

Types that are not duplicates are not marked as such.

<img width="738" alt="Screenshot 2019-09-09 at 16 42 37" src="https://user-images.githubusercontent.com/193115/64540838-1c148880-d321-11e9-9eec-c05603fe30af.png">

## Actual Behaviour

To be correctly marking duplicates and not marking non-duplicates as duplicates.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

```bash
echo "type A {
  a: String!
}" >types.graphql
# twice...
```

**Comment by jimkyndemeyer** [comment] 2019-09-10 12:21
Hi Henrik.

I tried to reproduce this based in the steps you described, but don't see any errors. Hmm..

![Sep-10-2019 14-18-00](https://user-images.githubusercontent.com/15837712/64613254-01501b80-d3d6-11e9-965f-b4448c419336.gif)

Have you tried "File" > "Synchronize" when you see the issue? This should refresh the index based on actual file system contents.

**Comment by haf** [comment] 2019-09-10 16:24
I can't reproduce this anymore. Did you push an update? I have not tried File > Syncronize, I'm afraid. Thanks for trying to repro it though.

**Comment by jimkyndemeyer** [comment] 2019-09-10 16:29
No updates, 2.2.0 is the latest version. I'll go ahead and close this for now. Will reopen if you add a comment in case you see it again.

**Closed by jimkyndemeyer** 2019-09-10 16:29 UTC

**Comment by dyst5422** [comment] 2020-08-06 23:17
I have this same issue in IntelliJ IDEA 2020.2

All projects with graphql complain about redefining existing types on every type definition

My .graphqlconfig looks like
```
{
  "name": "SeqVAL GraphQL Schema",
  "schemaPath": "src/schema.graphql"
}
```
with just that one schema graphql file. There are no other graphql files in my project.
