### ISSUE TITLE
Syntax error when interpolating fragments

### ISSUE THREAD

**Issue by almilo** [jimkyndemeyer/js-graphql-intellij-plugin#54] opened 2017-01-24 11:02 UTC
Hi,

Following the recommended approach to reuse fragments described here: http://dev.apollodata.com/react/fragments.html#reusing-fragments I get a: `Error:(79, 5) Syntax Error GraphQL (79:5) Unexpected Name "__typename"` where the first fragment is interpolated.

Example:
```javascript
const query = gql`
    query foos($id1: ID!, $id2: ID!) {
        bars(id1: $id1, id2: $id2) {
            thing1 {
                ...thingFragment
            }
            thing2 {
                ...thingFragment
            }
            thing3 {
                ...otherThingFragment
            }
        }
    }
    ${Comp1.fragment} # Comp1.fragment = gql`... fragment thingFragment on ...
    ${Comp2.fragment} # Comp2.fragment = gql`... fragment otherThingFragment on ...
`;
```

IDEA version: 2016.3.3
Plugin version: 1.4.4

Thanks in advance and congratulations for the awesome plugin!! :)
Alberto

**Comment by jimkyndemeyer** [comment] 2017-01-24 11:15
Hi Alberto.

Thanks for using the plugin.

This appears to be a duplicate of #44. Feel free to re-open if that's not the case.

/Jim.

**Closed by jimkyndemeyer** 2017-01-24 11:15 UTC
