### ISSUE TITLE
'Editor > Code Style' never loads In WebStorm 2017.3

### ISSUE THREAD

**Issue by ryanquinn3** [jimkyndemeyer/js-graphql-intellij-plugin#120] opened 2017-12-07 19:17 UTC
When navigating to the GraphQL file type under Code Style the preferences panel hangs like so:
![screen shot 2017-12-07 at 11 12 53 am](https://user-images.githubusercontent.com/5115565/33733832-d94de1e8-db3f-11e7-971a-d5f22444b2d4.png)

I'm using:
Webstorm 2017.3
Plugin v1.6.2
MacOS 10.12.6

**Comment by jimkyndemeyer** [comment] 2017-12-08 13:23
Hi Ryan.

Thanks for catching this.

It's working as intended in IntelliJ 2017.2.5, so it appears to be a compatibility issue with 2017.3

I'm hoping to get to this during the weekend.

/Jim.

**Comment by mariomka** [comment] 2017-12-27 13:28
The same issue in PhpStorm 2017.3.1.
I want to change indent to 2 spaces. Can you share XML section of code style file?

**Comment by ForsakenHarmony** [comment] 2017-12-30 18:24
when are you gonna release it?

**Comment by jimkyndemeyer** [comment] 2018-01-02 17:59
This is fixed in v1.6.3, pending JetBrains approval.

**Closed by jimkyndemeyer** 2018-01-02 17:59 UTC

**Comment by jimkyndemeyer** [comment] 2018-01-03 12:03
JetBrains just approved it, so should be available for update now.
