### ISSUE TITLE
Error: Mode graphql failed to advance stream

### ISSUE THREAD

**Issue by sedubois** [jimkyndemeyer/js-graphql-intellij-plugin#33] opened 2016-10-17 14:57 UTC
IntelliJ IDEA 2016.2.4 Build #IU-162.2032.8. I'm not quite sure what triggers this. I didn't see anything working wrong otherwise, just this error repeating in the GraphQL console. It is just annoying because the GraphQL console tab will then suddenly open.

```
Error: Mode graphql failed to advance stream.
    at readToken (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:24651:11)
    at runMode (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:24691:36)
    at highlightLine (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:24723:5)
    at getLineStyles (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:24759:20)
    at buildLineContent (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:24821:40)
    at updateExternalMeasurement (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:20432:30)
    at prepareMeasureForLine (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:20468:14)
    at measureChar (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:20441:36)
    at endOperation_R2 (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:20962:26)
    at endOperations (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:20928:7)
```

**Comment by jimkyndemeyer** [comment] 2016-10-17 15:06
I need some more information to reproduce this.
- The contents of the editor buffer
- Exact steps to reproduce (are you typing, at what position in the buffer, etc.)

**Comment by jimkyndemeyer** [comment] 2016-10-17 17:56
This appears to be related to `codemirror-graphql`.

To help reproduce it, I'd like you to edit `/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js` and add the following error logging.

Above line 162.530 containing `if(cmCurrentDocValue != textToParse)` add a new line containing `try {`

After `res.send(JSON.stringify(responseData));` at approx. line 162.559, add:

```
    } catch(e) {
      console.error('\n[ERROR] ' + new Date() + ':');
      console.error(e);
      console.error(JSON.stringify(requestData));
      console.error('\n');
    }
```

This should console.error the editor buffer that chokes `codemirror-graphql`.

**Comment by sedubois** [comment] 2016-10-18 07:44
Thanks I will, first I need to reproduce it.

**Comment by jimkyndemeyer** [comment] 2016-10-30 18:20
@sedubois Any updates on reproducing this?

**Comment by sedubois** [comment] 2016-10-30 18:22
Sorry no. It occurred around when I installed the plugin, but even when reinstalling and generally using GraphQL, I haven't seen it. Probably the bug is still there, just can't reproduce.

**Comment by jimkyndemeyer** [comment] 2016-10-30 18:27
Ok, thanks.

I'll close this for the time being since the call stack points at `codemirror-graphql` and not the plugin.

Feel free to drop a comment once you reproduce and we'll take it from there.

**Closed by jimkyndemeyer** 2016-10-30 18:27 UTC

**Comment by sedubois** [comment] 2016-10-31 10:04
I just got the error again, don't know if it relates to https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/37.

```
...
const MyQuery = gql`{
  allUsers {
    id
    giv(I then hit ctrl-space for autocompletion and the plugin displayed the error stack)
  }
}`;
...
```

**Comment by jimkyndemeyer** [comment] 2016-10-31 10:48
Did the fix for #37 remove the error?

**Comment by sedubois** [comment] 2016-10-31 10:50
I haven't seen it since...

**Comment by sedubois** [comment] 2016-11-08 13:40
I have the error again:
```
Error: Mode graphql failed to advance stream.
    at readToken (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:24651:11)
    at takeToken (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:24670:15)
    at CodeMirror.getLineTokens (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:22854:14)
    at getTokens (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:162653:25)
    at /Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:162539:24
    at Layer.handle [as handle_request] (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:29961:5)
    at next (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:30175:13)
    at next (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:30169:14)
    at next (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:30169:14)
    at next (/Users/sdubois/Library/Application Support/IntelliJIdea2016.2/js-graphql-language-service.dist.js:30169:14)
```

I had created an Apollo mutation:
```
const createUserMutation = gql`
  mutation createUser {
    
  }
`;
```
And got the stack traces printed every time when the cursor was in the brackets and I hit Alt-space (I think I intended to hit ctr-space to have the autocomplete popup, and mistook for alt-space).

**Comment by jimkyndemeyer** [comment] 2016-11-08 14:26
Thanks for the update.

It appears that alt+space produces character code 160 (a non-breaking whitespace) which codemirror-graphql doesn't handle in the version that's included with the plugin.

I'll investigate a fix and release the plugin with an updated version.

/Jim.

**Comment by sedubois** [comment] 2016-11-08 14:28
Thanks! 👍
