### ISSUE TITLE
Support triple-double-quote """block quotes""".

### ISSUE THREAD

**Issue by estaub** [jimkyndemeyer/js-graphql-intellij-plugin#156] opened 2018-05-18 02:41 UTC
Graphql 1.2 and beyond supports using triple-double-quotes to bracket block strings.
See [the draft spec](http://facebook.github.io/graphql/draft/#sec-String-Value). 

graphql-cli is now emitting them in schema.

**Comment by jimkyndemeyer** [comment] 2018-05-18 17:31
Duplicate of #118

**Closed by jimkyndemeyer** 2018-05-18 17:31 UTC
