### ISSUE TITLE
Latest version 2.1.0 has issues with Long, Query and Mutation type

### ISSUE THREAD

**Issue by micobarac** [jimkyndemeyer/js-graphql-intellij-plugin#245] opened 2019-04-18 12:52 UTC
## Version and Environment Details
__Operation system__: 
darwin x64

__IDE name and version__: 
Intellij IDEA 2019.1

__Plugin version__: 
2.1.0

## Expected Behaviour
1. `Long` type should be allowed
2. Detecting `Query` and `Mutation` type root definitions should work as expected

## Actual Behaviour
1. As ID type produces String value, I had to switch to Long type, to match MySQL autoincrement data type:
![Screenshot 2019-04-18 at 14 53 15](https://user-images.githubusercontent.com/16001837/56362288-be549800-61e9-11e9-8909-4ea6fb019b1d.png)

2. I have multiple schema files, but only here I have defined the root Query and Mutation types. Still, the error is thrown:
![Screenshot 2019-04-18 at 14 49 40](https://user-images.githubusercontent.com/16001837/56362061-3b334200-61e9-11e9-80be-459257f145f1.png)

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
`book.graphqls`

```graphql
type Book {
    id: Long!
    title: String!
    isbn: String!
    pages: Int
    author: Author
}

input CreateBookInput {
    title: String!
    isbn: String!
    pages: Int
    author: Long!
}

input UpdateBookInput {
    id: Long!
    pages: Int!
}

type Query {
    findAllBooks: [Book]!
    countBooks: Long!
}

type Mutation {
    newBook(input: CreateBookInput!): Book!
    deleteBook(id: Long!): Boolean
    updateBookPages(input: UpdateBookInput!): Book!
}
```

`author.graphqls`

```graphql
type Author {
    id: Long!
    firstName: String!
    lastName: String!
    books: [Book]!
}

input CreateAuthorInput {
    firstName: String!
    lastName: String!
}

extend type Query {
    findAllAuthors: [Author]!
    countAuthors: Long!
}

extend type Mutation {
    newAuthor(input: CreateAuthorInput!): Author!
}
```

**Comment by jimkyndemeyer** [comment] 2019-04-18 18:12
Hi Milan.

Thanks for using the plugin.

I created a blank project and created the two graphqls files you listed. The only errors I see relate to the use of the `Long` type that is not a part of the built-in GraphQL scalars. You can fix that by declaring it in your schema as follows:

```graphql
scalar Long
```

With that I see the schema without errors as follows:

![image](https://user-images.githubusercontent.com/15837712/56381574-90854880-6215-11e9-8f2e-2b8b3b0cdae7.png)

I think it's likely that you have duplicate a `Query` and `Mutation` definition somewhere in your project. If you had a JSON file as your `schemaPath` in your config make sure that it's no longer part of your project.

If that's not the issue I suggest you try the following:
- In book.graphqls comment out the Query definition
- In author.graphql you should be able to cmd+click Query in the extend statement to see where the plugin picks up the unexpected definition.

I hope that gets the schema working for you.

Best regards,
Jim.

**Comment by dandrei** [comment] 2019-04-22 15:30
@jimkyndemeyer I have a similar issue. I define the schema inside JS code, like so:

    const typeDefs = gql`
        type Query {
            MY QUERIES HERE
        }
    
        type Mutation {
            MY MUTATIONS HERE
        }
    `;
    
    const resolvers = {
        Query: {
            // MY CODE HERE
        },
        
        Mutation: {
            // MY CODE HERE
        }
    }
    
    export default makeExecutableSchema({typeDefs, resolvers});

I have several files that work like this. I then initialize ApolloServer like so:

    new ApolloServer(schema: mergeSchemas({schemas: [ /* all imported schemas */]}));

But on random files, I get one of the following:
- `'Query' type [@L,N] tried to redefine existing 'Query' type [@L,N]`
- `'Mutation' type [@L,N] tried to redefine existing 'Mutation' type [@L,N]`

Not sure how to make the errors go away. Help appreciated, thanks!

**Comment by sbuljac** [comment] 2019-04-23 11:21
I have the same issue as @dandrei.

**Comment by zenonwch** [comment] 2019-04-30 07:00
Faced the same issue with the v 2.1.0
![image](https://user-images.githubusercontent.com/17174214/56945103-8d039280-6b2e-11e9-868e-d6bb13f3b51e.png)
![image](https://user-images.githubusercontent.com/17174214/56945132-ac022480-6b2e-11e9-9534-de47ac9f6a44.png)

**Comment by jimkyndemeyer** [comment] 2019-05-03 08:35
@dandrei @sbuljac Please take a look at https://github.com/jimkyndemeyer/graphql-config-examples and the `extend-client-fields-and-directives` for an example of how to make discovery work in an Apollo project.

**Comment by jimkyndemeyer** [comment] 2019-05-31 11:46
I'm closing this based on the suggestions I made above.

A small example project that reproduces the issue is needed to make further action from my side possible.

**Closed by jimkyndemeyer** 2019-05-31 11:46 UTC
